# Vectores y Matrices con Numpy

## Vectores

In [1]:
import numpy as np

In [2]:
x=[1,2,3,4,5,6,4,8] #lista

In [3]:
x=np.array(x) #convertir lista en vector
print(x)

[1 2 3 4 5 6 4 8]


In [4]:
v=np.ones(3)#vector de 1 de dimensión 3
print(v)

[1. 1. 1.]


In [5]:
v3 = np.array([1, 3, 5])#introducir números manualmente
print(v3)

[1 3 5]


In [6]:
v4 = np.arange(1, 8) #vector ontiene números de 1 al 7
print(v4)

[1 2 3 4 5 6 7]


In [7]:
x = np.arange(1, 5)
print(x)

[1 2 3 4]


In [8]:
y = np.array([2, 4, 6, 8])
print(y)

[2 4 6 8]


In [9]:
print(x,y)

[1 2 3 4] [2 4 6 8]


In [10]:
print(x + y) #Suma de vectores

[ 3  6  9 12]


In [11]:
print(x - y) #Resta de vectores

[-1 -2 -3 -4]


In [12]:
print(x*2) #producto escalar

[2 4 6 8]


In [13]:
print(np.dot(x, y)) #producto punto

60


In [14]:
print(np.linalg.norm(x)) #Norma

5.477225575051661


# Matrices

In [15]:
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])
print(A)

[[1 3 2]
 [1 0 0]
 [1 2 2]]


In [16]:
B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])
print(B)

[[1 0 5]
 [7 5 0]
 [2 1 1]]


In [17]:
print(A+B) #Suma de matrices

[[2 3 7]
 [8 5 0]
 [3 3 3]]


In [18]:
print(A-B) #Resta de matrices

[[ 0  3 -3]
 [-6 -5  0]
 [-1  1  1]]


In [19]:
print(A*3) #Producto Escalar

[[3 9 6]
 [3 0 0]
 [3 6 6]]


In [20]:
B.shape #Dimensión

(3, 3)

In [21]:
A.size #Número de elementos de la matriz

9

In [22]:
A = np.arange(1, 13).reshape(3, 4) #Matriz de 1 al 12 y de 3 x 4
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
B = np.arange(8).reshape(4,2)
print(B)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [24]:
A @ B #Producto matricial

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [25]:
I = np.eye(2) #Matriz identidad de 2x2
print(I)

[[1. 0.]
 [0. 1.]]


In [26]:
A = np.array([[4, 7],
              [2, 6]])
np.linalg.det(A) #Determinante de A

10.000000000000002

In [27]:
A_inv = np.linalg.inv(A) #inversa
print(A_inv)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [28]:
A = np.arange(6).reshape(3, 2)
print(A)
np.transpose(A)#Transpuesta

[[0 1]
 [2 3]
 [4 5]]


array([[0, 2, 4],
       [1, 3, 5]])

# Solución de sistemas de Ecuaciones

In [29]:
A = np.array([[1, 2, 3], #Matriz de coeficientes
              [2, 5, 2],
              [6, -3, 1]])
print(A)

[[ 1  2  3]
 [ 2  5  2]
 [ 6 -3  1]]


In [30]:
b = np.array([6, 4, 2])#Solución
print(b)

[6 4 2]


In [31]:
x = np.linalg.solve(A, b)#resolviendo
print(x)

[0. 0. 2.]


In [32]:
print(A @ x == b)

[ True  True  True]
